### ISSUE TITLE
Cannot run one liner directly from package.json - env-cmd sh -c \"echo $SOME_VAR\" doesn't seem to work.

### ISSUE THREAD

**Issue by ghost** [toddbluhm/env-cmd-examples#3]
Hi.

My .env

```
SOME_VAR=milk
```

My script inside package json

```
"scripts": {
   "expected_to_work": "env-cmd sh test.sh",
   "expected_to_fail": " sh test.sh",
   "why_doesnt_this_work": "env-cmd sh -c \"echo $SOME_VAR\""
}
````

test.sh

```
echo $SOME_VAR
```

`yarn expected_to_work` echoes 'milk', `yarn expected_to_fail` doesn't, just as expected. 
However `yarn why_doesnt_this_work` doesn't pass the .env variables to sh

**Comment by toddbluhm** [comment]
Sorry for the extreme delay on this issue. Per the README file, I do not often check this repo's issues.

I believe if you pass `--use-shell` option to `env-cmd` it might work. I am not exactly sure why it does not work. I have heard/seen/read various explanations, but I am not 100% sure. The reason I usually give is that `echo $SOME_VAR` is being executing in the current shell context rather than in the new context were the env vars are set. The gist of it is, just do not use `env-cmd` in that way.

**Comment by toddbluhm** [comment]
Closing as stale.
